#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tesis")]
	public partial class dbTICsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProcesos(Procesos instance);
    partial void UpdateProcesos(Procesos instance);
    partial void DeleteProcesos(Procesos instance);
    partial void InsertRecorridoVirtual(RecorridoVirtual instance);
    partial void UpdateRecorridoVirtual(RecorridoVirtual instance);
    partial void DeleteRecorridoVirtual(RecorridoVirtual instance);
    partial void InsertAdministradores(Administradores instance);
    partial void UpdateAdministradores(Administradores instance);
    partial void DeleteAdministradores(Administradores instance);
    partial void InsertUnidades(Unidades instance);
    partial void UpdateUnidades(Unidades instance);
    partial void DeleteUnidades(Unidades instance);
    partial void InsertCamposFormacion(CamposFormacion instance);
    partial void UpdateCamposFormacion(CamposFormacion instance);
    partial void DeleteCamposFormacion(CamposFormacion instance);
    partial void InsertObjetivosAprendizaje(ObjetivosAprendizaje instance);
    partial void UpdateObjetivosAprendizaje(ObjetivosAprendizaje instance);
    partial void DeleteObjetivosAprendizaje(ObjetivosAprendizaje instance);
    partial void InsertMallaCurricular(MallaCurricular instance);
    partial void UpdateMallaCurricular(MallaCurricular instance);
    partial void DeleteMallaCurricular(MallaCurricular instance);
    partial void InsertPrerrequisito(Prerrequisito instance);
    partial void UpdatePrerrequisito(Prerrequisito instance);
    partial void DeletePrerrequisito(Prerrequisito instance);
    partial void InsertGraduados(Graduados instance);
    partial void UpdateGraduados(Graduados instance);
    partial void DeleteGraduados(Graduados instance);
    partial void InsertMatriculados(Matriculados instance);
    partial void UpdateMatriculados(Matriculados instance);
    partial void DeleteMatriculados(Matriculados instance);
    partial void InsertMensajesMaGra(MensajesMaGra instance);
    partial void UpdateMensajesMaGra(MensajesMaGra instance);
    partial void DeleteMensajesMaGra(MensajesMaGra instance);
    partial void InsertFormSoli(FormSoli instance);
    partial void UpdateFormSoli(FormSoli instance);
    partial void DeleteFormSoli(FormSoli instance);
    partial void InsertAsignaturas(Asignaturas instance);
    partial void UpdateAsignaturas(Asignaturas instance);
    partial void DeleteAsignaturas(Asignaturas instance);
    #endregion
		
		public dbTICsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TesisConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbTICsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTICsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTICsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTICsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Procesos> Procesos
		{
			get
			{
				return this.GetTable<Procesos>();
			}
		}
		
		public System.Data.Linq.Table<RecorridoVirtual> RecorridoVirtual
		{
			get
			{
				return this.GetTable<RecorridoVirtual>();
			}
		}
		
		public System.Data.Linq.Table<Administradores> Administradores
		{
			get
			{
				return this.GetTable<Administradores>();
			}
		}
		
		public System.Data.Linq.Table<Unidades> Unidades
		{
			get
			{
				return this.GetTable<Unidades>();
			}
		}
		
		public System.Data.Linq.Table<CamposFormacion> CamposFormacion
		{
			get
			{
				return this.GetTable<CamposFormacion>();
			}
		}
		
		public System.Data.Linq.Table<ObjetivosAprendizaje> ObjetivosAprendizaje
		{
			get
			{
				return this.GetTable<ObjetivosAprendizaje>();
			}
		}
		
		public System.Data.Linq.Table<MallaCurricular> MallaCurricular
		{
			get
			{
				return this.GetTable<MallaCurricular>();
			}
		}
		
		public System.Data.Linq.Table<Prerrequisito> Prerrequisito
		{
			get
			{
				return this.GetTable<Prerrequisito>();
			}
		}
		
		public System.Data.Linq.Table<Graduados> Graduados
		{
			get
			{
				return this.GetTable<Graduados>();
			}
		}
		
		public System.Data.Linq.Table<Matriculados> Matriculados
		{
			get
			{
				return this.GetTable<Matriculados>();
			}
		}
		
		public System.Data.Linq.Table<MensajesMaGra> MensajesMaGra
		{
			get
			{
				return this.GetTable<MensajesMaGra>();
			}
		}
		
		public System.Data.Linq.Table<FormSoli> FormSoli
		{
			get
			{
				return this.GetTable<FormSoli>();
			}
		}
		
		public System.Data.Linq.Table<Asignaturas> Asignaturas
		{
			get
			{
				return this.GetTable<Asignaturas>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proalmColumna")]
		public ISingleResult<proalmColumnaResult> proalmColumna([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idmalla)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idmalla);
			return ((ISingleResult<proalmColumnaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proalmSemestre")]
		public ISingleResult<proalmSemestreResult> proalmSemestre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idmalla)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idmalla);
			return ((ISingleResult<proalmSemestreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.palmaTodasAsignaturas")]
		public ISingleResult<palmaTodasAsignaturasResult> palmaTodasAsignaturas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idmalla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> asignatura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idmalla, asignatura);
			return ((ISingleResult<palmaTodasAsignaturasResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Procesos")]
	public partial class Procesos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProceso;
		
		private string _NombreProceso;
		
		private string _Proceso;
		
		private string _Reglamentacion;
		
		private System.Nullable<int> _IdMalla;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProcesoChanging(int value);
    partial void OnIdProcesoChanged();
    partial void OnNombreProcesoChanging(string value);
    partial void OnNombreProcesoChanged();
    partial void OnProcesoChanging(string value);
    partial void OnProcesoChanged();
    partial void OnReglamentacionChanging(string value);
    partial void OnReglamentacionChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public Procesos()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProceso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdProceso
		{
			get
			{
				return this._IdProceso;
			}
			set
			{
				if ((this._IdProceso != value))
				{
					this.OnIdProcesoChanging(value);
					this.SendPropertyChanging();
					this._IdProceso = value;
					this.SendPropertyChanged("IdProceso");
					this.OnIdProcesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProceso", DbType="VarChar(MAX)")]
		public string NombreProceso
		{
			get
			{
				return this._NombreProceso;
			}
			set
			{
				if ((this._NombreProceso != value))
				{
					this.OnNombreProcesoChanging(value);
					this.SendPropertyChanging();
					this._NombreProceso = value;
					this.SendPropertyChanged("NombreProceso");
					this.OnNombreProcesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proceso", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Proceso
		{
			get
			{
				return this._Proceso;
			}
			set
			{
				if ((this._Proceso != value))
				{
					this.OnProcesoChanging(value);
					this.SendPropertyChanging();
					this._Proceso = value;
					this.SendPropertyChanged("Proceso");
					this.OnProcesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reglamentacion", DbType="VarChar(MAX)")]
		public string Reglamentacion
		{
			get
			{
				return this._Reglamentacion;
			}
			set
			{
				if ((this._Reglamentacion != value))
				{
					this.OnReglamentacionChanging(value);
					this.SendPropertyChanging();
					this._Reglamentacion = value;
					this.SendPropertyChanged("Reglamentacion");
					this.OnReglamentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Procesos", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.Procesos.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.Procesos.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecorridoVirtual")]
	public partial class RecorridoVirtual : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRecorrido;
		
		private string _NombreLaboratorio;
		
		private string _Laboratorio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRecorridoChanging(int value);
    partial void OnIdRecorridoChanged();
    partial void OnNombreLaboratorioChanging(string value);
    partial void OnNombreLaboratorioChanged();
    partial void OnLaboratorioChanging(string value);
    partial void OnLaboratorioChanged();
    #endregion
		
		public RecorridoVirtual()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecorrido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRecorrido
		{
			get
			{
				return this._IdRecorrido;
			}
			set
			{
				if ((this._IdRecorrido != value))
				{
					this.OnIdRecorridoChanging(value);
					this.SendPropertyChanging();
					this._IdRecorrido = value;
					this.SendPropertyChanged("IdRecorrido");
					this.OnIdRecorridoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreLaboratorio", DbType="VarChar(MAX)")]
		public string NombreLaboratorio
		{
			get
			{
				return this._NombreLaboratorio;
			}
			set
			{
				if ((this._NombreLaboratorio != value))
				{
					this.OnNombreLaboratorioChanging(value);
					this.SendPropertyChanging();
					this._NombreLaboratorio = value;
					this.SendPropertyChanged("NombreLaboratorio");
					this.OnNombreLaboratorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Laboratorio", DbType="VarChar(50)")]
		public string Laboratorio
		{
			get
			{
				return this._Laboratorio;
			}
			set
			{
				if ((this._Laboratorio != value))
				{
					this.OnLaboratorioChanging(value);
					this.SendPropertyChanging();
					this._Laboratorio = value;
					this.SendPropertyChanged("Laboratorio");
					this.OnLaboratorioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administradores")]
	public partial class Administradores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAdmin;
		
		private string _Nombre;
		
		private string _Cargo;
		
		private string _Correo;
		
		private string _Usuario;
		
		private string _Contraseña;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAdminChanging(int value);
    partial void OnIdAdminChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public Administradores()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAdmin
		{
			get
			{
				return this._IdAdmin;
			}
			set
			{
				if ((this._IdAdmin != value))
				{
					this.OnIdAdminChanging(value);
					this.SendPropertyChanging();
					this._IdAdmin = value;
					this.SendPropertyChanged("IdAdmin");
					this.OnIdAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(50)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Unidades")]
	public partial class Unidades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUnidades;
		
		private string _NombreUnidad;
		
		private System.Nullable<int> _Horas;
		
		private System.Nullable<int> _IdMalla;
		
		private EntitySet<Asignaturas> _Asignaturas;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUnidadesChanging(int value);
    partial void OnIdUnidadesChanged();
    partial void OnNombreUnidadChanging(string value);
    partial void OnNombreUnidadChanged();
    partial void OnHorasChanging(System.Nullable<int> value);
    partial void OnHorasChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public Unidades()
		{
			this._Asignaturas = new EntitySet<Asignaturas>(new Action<Asignaturas>(this.attach_Asignaturas), new Action<Asignaturas>(this.detach_Asignaturas));
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnidades", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUnidades
		{
			get
			{
				return this._IdUnidades;
			}
			set
			{
				if ((this._IdUnidades != value))
				{
					this.OnIdUnidadesChanging(value);
					this.SendPropertyChanging();
					this._IdUnidades = value;
					this.SendPropertyChanged("IdUnidades");
					this.OnIdUnidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUnidad", DbType="VarChar(50)")]
		public string NombreUnidad
		{
			get
			{
				return this._NombreUnidad;
			}
			set
			{
				if ((this._NombreUnidad != value))
				{
					this.OnNombreUnidadChanging(value);
					this.SendPropertyChanging();
					this._NombreUnidad = value;
					this.SendPropertyChanged("NombreUnidad");
					this.OnNombreUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas", DbType="Int")]
		public System.Nullable<int> Horas
		{
			get
			{
				return this._Horas;
			}
			set
			{
				if ((this._Horas != value))
				{
					this.OnHorasChanging(value);
					this.SendPropertyChanging();
					this._Horas = value;
					this.SendPropertyChanged("Horas");
					this.OnHorasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unidades_Asignaturas", Storage="_Asignaturas", ThisKey="IdUnidades", OtherKey="IdUnidad")]
		public EntitySet<Asignaturas> Asignaturas
		{
			get
			{
				return this._Asignaturas;
			}
			set
			{
				this._Asignaturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Unidades", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.Unidades.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.Unidades.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asignaturas(Asignaturas entity)
		{
			this.SendPropertyChanging();
			entity.Unidades = this;
		}
		
		private void detach_Asignaturas(Asignaturas entity)
		{
			this.SendPropertyChanging();
			entity.Unidades = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CamposFormacion")]
	public partial class CamposFormacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCampo;
		
		private string _SiglasCampo;
		
		private string _NombreCampo;
		
		private System.Nullable<int> _Horas;
		
		private System.Nullable<int> _IdMalla;
		
		private string _Color;
		
		private EntitySet<Asignaturas> _Asignaturas;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCampoChanging(int value);
    partial void OnIdCampoChanged();
    partial void OnSiglasCampoChanging(string value);
    partial void OnSiglasCampoChanged();
    partial void OnNombreCampoChanging(string value);
    partial void OnNombreCampoChanged();
    partial void OnHorasChanging(System.Nullable<int> value);
    partial void OnHorasChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    #endregion
		
		public CamposFormacion()
		{
			this._Asignaturas = new EntitySet<Asignaturas>(new Action<Asignaturas>(this.attach_Asignaturas), new Action<Asignaturas>(this.detach_Asignaturas));
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCampo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCampo
		{
			get
			{
				return this._IdCampo;
			}
			set
			{
				if ((this._IdCampo != value))
				{
					this.OnIdCampoChanging(value);
					this.SendPropertyChanging();
					this._IdCampo = value;
					this.SendPropertyChanged("IdCampo");
					this.OnIdCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiglasCampo", DbType="VarChar(50)")]
		public string SiglasCampo
		{
			get
			{
				return this._SiglasCampo;
			}
			set
			{
				if ((this._SiglasCampo != value))
				{
					this.OnSiglasCampoChanging(value);
					this.SendPropertyChanging();
					this._SiglasCampo = value;
					this.SendPropertyChanged("SiglasCampo");
					this.OnSiglasCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCampo", DbType="VarChar(MAX)")]
		public string NombreCampo
		{
			get
			{
				return this._NombreCampo;
			}
			set
			{
				if ((this._NombreCampo != value))
				{
					this.OnNombreCampoChanging(value);
					this.SendPropertyChanging();
					this._NombreCampo = value;
					this.SendPropertyChanged("NombreCampo");
					this.OnNombreCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas", DbType="Int")]
		public System.Nullable<int> Horas
		{
			get
			{
				return this._Horas;
			}
			set
			{
				if ((this._Horas != value))
				{
					this.OnHorasChanging(value);
					this.SendPropertyChanging();
					this._Horas = value;
					this.SendPropertyChanged("Horas");
					this.OnHorasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CamposFormacion_Asignaturas", Storage="_Asignaturas", ThisKey="IdCampo", OtherKey="IdCampo")]
		public EntitySet<Asignaturas> Asignaturas
		{
			get
			{
				return this._Asignaturas;
			}
			set
			{
				this._Asignaturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_CamposFormacion", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.CamposFormacion.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.CamposFormacion.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asignaturas(Asignaturas entity)
		{
			this.SendPropertyChanging();
			entity.CamposFormacion = this;
		}
		
		private void detach_Asignaturas(Asignaturas entity)
		{
			this.SendPropertyChanging();
			entity.CamposFormacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObjetivosAprendizaje")]
	public partial class ObjetivosAprendizaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdObjetivo;
		
		private string _NombreObj;
		
		private string _Objetivo;
		
		private System.Nullable<int> _IdMalla;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdObjetivoChanging(int value);
    partial void OnIdObjetivoChanged();
    partial void OnNombreObjChanging(string value);
    partial void OnNombreObjChanged();
    partial void OnObjetivoChanging(string value);
    partial void OnObjetivoChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public ObjetivosAprendizaje()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdObjetivo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdObjetivo
		{
			get
			{
				return this._IdObjetivo;
			}
			set
			{
				if ((this._IdObjetivo != value))
				{
					this.OnIdObjetivoChanging(value);
					this.SendPropertyChanging();
					this._IdObjetivo = value;
					this.SendPropertyChanged("IdObjetivo");
					this.OnIdObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreObj", DbType="VarChar(50)")]
		public string NombreObj
		{
			get
			{
				return this._NombreObj;
			}
			set
			{
				if ((this._NombreObj != value))
				{
					this.OnNombreObjChanging(value);
					this.SendPropertyChanging();
					this._NombreObj = value;
					this.SendPropertyChanged("NombreObj");
					this.OnNombreObjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objetivo", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Objetivo
		{
			get
			{
				return this._Objetivo;
			}
			set
			{
				if ((this._Objetivo != value))
				{
					this.OnObjetivoChanging(value);
					this.SendPropertyChanging();
					this._Objetivo = value;
					this.SendPropertyChanged("Objetivo");
					this.OnObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_ObjetivosAprendizaje", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.ObjetivosAprendizaje.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.ObjetivosAprendizaje.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MallaCurricular")]
	public partial class MallaCurricular : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMalla;
		
		private string _NombreMalla;
		
		private string _Pensum;
		
		private string _Estado;
		
		private EntitySet<Procesos> _Procesos;
		
		private EntitySet<Unidades> _Unidades;
		
		private EntitySet<CamposFormacion> _CamposFormacion;
		
		private EntitySet<ObjetivosAprendizaje> _ObjetivosAprendizaje;
		
		private EntitySet<Prerrequisito> _Prerrequisito;
		
		private EntitySet<Graduados> _Graduados;
		
		private EntitySet<Matriculados> _Matriculados;
		
		private EntitySet<MensajesMaGra> _MensajesMaGra;
		
		private EntitySet<FormSoli> _FormSoli;
		
		private EntitySet<Asignaturas> _Asignaturas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMallaChanging(int value);
    partial void OnIdMallaChanged();
    partial void OnNombreMallaChanging(string value);
    partial void OnNombreMallaChanged();
    partial void OnPensumChanging(string value);
    partial void OnPensumChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public MallaCurricular()
		{
			this._Procesos = new EntitySet<Procesos>(new Action<Procesos>(this.attach_Procesos), new Action<Procesos>(this.detach_Procesos));
			this._Unidades = new EntitySet<Unidades>(new Action<Unidades>(this.attach_Unidades), new Action<Unidades>(this.detach_Unidades));
			this._CamposFormacion = new EntitySet<CamposFormacion>(new Action<CamposFormacion>(this.attach_CamposFormacion), new Action<CamposFormacion>(this.detach_CamposFormacion));
			this._ObjetivosAprendizaje = new EntitySet<ObjetivosAprendizaje>(new Action<ObjetivosAprendizaje>(this.attach_ObjetivosAprendizaje), new Action<ObjetivosAprendizaje>(this.detach_ObjetivosAprendizaje));
			this._Prerrequisito = new EntitySet<Prerrequisito>(new Action<Prerrequisito>(this.attach_Prerrequisito), new Action<Prerrequisito>(this.detach_Prerrequisito));
			this._Graduados = new EntitySet<Graduados>(new Action<Graduados>(this.attach_Graduados), new Action<Graduados>(this.detach_Graduados));
			this._Matriculados = new EntitySet<Matriculados>(new Action<Matriculados>(this.attach_Matriculados), new Action<Matriculados>(this.detach_Matriculados));
			this._MensajesMaGra = new EntitySet<MensajesMaGra>(new Action<MensajesMaGra>(this.attach_MensajesMaGra), new Action<MensajesMaGra>(this.detach_MensajesMaGra));
			this._FormSoli = new EntitySet<FormSoli>(new Action<FormSoli>(this.attach_FormSoli), new Action<FormSoli>(this.detach_FormSoli));
			this._Asignaturas = new EntitySet<Asignaturas>(new Action<Asignaturas>(this.attach_Asignaturas), new Action<Asignaturas>(this.detach_Asignaturas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMalla", DbType="VarChar(MAX)")]
		public string NombreMalla
		{
			get
			{
				return this._NombreMalla;
			}
			set
			{
				if ((this._NombreMalla != value))
				{
					this.OnNombreMallaChanging(value);
					this.SendPropertyChanging();
					this._NombreMalla = value;
					this.SendPropertyChanged("NombreMalla");
					this.OnNombreMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pensum", DbType="VarChar(50)")]
		public string Pensum
		{
			get
			{
				return this._Pensum;
			}
			set
			{
				if ((this._Pensum != value))
				{
					this.OnPensumChanging(value);
					this.SendPropertyChanging();
					this._Pensum = value;
					this.SendPropertyChanged("Pensum");
					this.OnPensumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Procesos", Storage="_Procesos", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<Procesos> Procesos
		{
			get
			{
				return this._Procesos;
			}
			set
			{
				this._Procesos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Unidades", Storage="_Unidades", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<Unidades> Unidades
		{
			get
			{
				return this._Unidades;
			}
			set
			{
				this._Unidades.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_CamposFormacion", Storage="_CamposFormacion", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<CamposFormacion> CamposFormacion
		{
			get
			{
				return this._CamposFormacion;
			}
			set
			{
				this._CamposFormacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_ObjetivosAprendizaje", Storage="_ObjetivosAprendizaje", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<ObjetivosAprendizaje> ObjetivosAprendizaje
		{
			get
			{
				return this._ObjetivosAprendizaje;
			}
			set
			{
				this._ObjetivosAprendizaje.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Prerrequisito", Storage="_Prerrequisito", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<Prerrequisito> Prerrequisito
		{
			get
			{
				return this._Prerrequisito;
			}
			set
			{
				this._Prerrequisito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Graduados", Storage="_Graduados", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<Graduados> Graduados
		{
			get
			{
				return this._Graduados;
			}
			set
			{
				this._Graduados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Matriculados", Storage="_Matriculados", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<Matriculados> Matriculados
		{
			get
			{
				return this._Matriculados;
			}
			set
			{
				this._Matriculados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_MensajesMaGra", Storage="_MensajesMaGra", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<MensajesMaGra> MensajesMaGra
		{
			get
			{
				return this._MensajesMaGra;
			}
			set
			{
				this._MensajesMaGra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_FormSoli", Storage="_FormSoli", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<FormSoli> FormSoli
		{
			get
			{
				return this._FormSoli;
			}
			set
			{
				this._FormSoli.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Asignaturas", Storage="_Asignaturas", ThisKey="IdMalla", OtherKey="IdMalla")]
		public EntitySet<Asignaturas> Asignaturas
		{
			get
			{
				return this._Asignaturas;
			}
			set
			{
				this._Asignaturas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Procesos(Procesos entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_Procesos(Procesos entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_Unidades(Unidades entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_Unidades(Unidades entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_CamposFormacion(CamposFormacion entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_CamposFormacion(CamposFormacion entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_ObjetivosAprendizaje(ObjetivosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_ObjetivosAprendizaje(ObjetivosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_Prerrequisito(Prerrequisito entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_Prerrequisito(Prerrequisito entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_Graduados(Graduados entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_Graduados(Graduados entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_Matriculados(Matriculados entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_Matriculados(Matriculados entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_MensajesMaGra(MensajesMaGra entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_MensajesMaGra(MensajesMaGra entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_FormSoli(FormSoli entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_FormSoli(FormSoli entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
		
		private void attach_Asignaturas(Asignaturas entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = this;
		}
		
		private void detach_Asignaturas(Asignaturas entity)
		{
			this.SendPropertyChanging();
			entity.MallaCurricular = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prerrequisito")]
	public partial class Prerrequisito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPre;
		
		private System.Nullable<int> _IdAsignatura;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private System.Nullable<int> _IdMalla;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
		private EntityRef<Asignaturas> _Asignaturas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPreChanging(int value);
    partial void OnIdPreChanged();
    partial void OnIdAsignaturaChanging(System.Nullable<int> value);
    partial void OnIdAsignaturaChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public Prerrequisito()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			this._Asignaturas = default(EntityRef<Asignaturas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPre", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPre
		{
			get
			{
				return this._IdPre;
			}
			set
			{
				if ((this._IdPre != value))
				{
					this.OnIdPreChanging(value);
					this.SendPropertyChanging();
					this._IdPre = value;
					this.SendPropertyChanged("IdPre");
					this.OnIdPreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsignatura", DbType="Int")]
		public System.Nullable<int> IdAsignatura
		{
			get
			{
				return this._IdAsignatura;
			}
			set
			{
				if ((this._IdAsignatura != value))
				{
					if (this._Asignaturas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAsignaturaChanging(value);
					this.SendPropertyChanging();
					this._IdAsignatura = value;
					this.SendPropertyChanged("IdAsignatura");
					this.OnIdAsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(50)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(150)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Prerrequisito", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.Prerrequisito.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.Prerrequisito.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asignaturas_Prerrequisito", Storage="_Asignaturas", ThisKey="IdAsignatura", OtherKey="IdAsignatura", IsForeignKey=true)]
		public Asignaturas Asignaturas
		{
			get
			{
				return this._Asignaturas.Entity;
			}
			set
			{
				Asignaturas previousValue = this._Asignaturas.Entity;
				if (((previousValue != value) 
							|| (this._Asignaturas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asignaturas.Entity = null;
						previousValue.Prerrequisito.Remove(this);
					}
					this._Asignaturas.Entity = value;
					if ((value != null))
					{
						value.Prerrequisito.Add(this);
						this._IdAsignatura = value.IdAsignatura;
					}
					else
					{
						this._IdAsignatura = default(Nullable<int>);
					}
					this.SendPropertyChanged("Asignaturas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Graduados")]
	public partial class Graduados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGraduados;
		
		private string _Periodo;
		
		private System.Nullable<int> _Hombres;
		
		private System.Nullable<int> _Mujeres;
		
		private System.Nullable<int> _IdMalla;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGraduadosChanging(int value);
    partial void OnIdGraduadosChanged();
    partial void OnPeriodoChanging(string value);
    partial void OnPeriodoChanged();
    partial void OnHombresChanging(System.Nullable<int> value);
    partial void OnHombresChanged();
    partial void OnMujeresChanging(System.Nullable<int> value);
    partial void OnMujeresChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public Graduados()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGraduados", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdGraduados
		{
			get
			{
				return this._IdGraduados;
			}
			set
			{
				if ((this._IdGraduados != value))
				{
					this.OnIdGraduadosChanging(value);
					this.SendPropertyChanging();
					this._IdGraduados = value;
					this.SendPropertyChanged("IdGraduados");
					this.OnIdGraduadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="VarChar(6)")]
		public string Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this.OnPeriodoChanging(value);
					this.SendPropertyChanging();
					this._Periodo = value;
					this.SendPropertyChanged("Periodo");
					this.OnPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hombres", DbType="Int")]
		public System.Nullable<int> Hombres
		{
			get
			{
				return this._Hombres;
			}
			set
			{
				if ((this._Hombres != value))
				{
					this.OnHombresChanging(value);
					this.SendPropertyChanging();
					this._Hombres = value;
					this.SendPropertyChanged("Hombres");
					this.OnHombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mujeres", DbType="Int")]
		public System.Nullable<int> Mujeres
		{
			get
			{
				return this._Mujeres;
			}
			set
			{
				if ((this._Mujeres != value))
				{
					this.OnMujeresChanging(value);
					this.SendPropertyChanging();
					this._Mujeres = value;
					this.SendPropertyChanged("Mujeres");
					this.OnMujeresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Graduados", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.Graduados.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.Graduados.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Matriculados")]
	public partial class Matriculados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMatriculados;
		
		private string _Periodo;
		
		private System.Nullable<int> _Hombres;
		
		private System.Nullable<int> _Mujeres;
		
		private System.Nullable<int> _IdMalla;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMatriculadosChanging(int value);
    partial void OnIdMatriculadosChanged();
    partial void OnPeriodoChanging(string value);
    partial void OnPeriodoChanged();
    partial void OnHombresChanging(System.Nullable<int> value);
    partial void OnHombresChanged();
    partial void OnMujeresChanging(System.Nullable<int> value);
    partial void OnMujeresChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public Matriculados()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMatriculados", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMatriculados
		{
			get
			{
				return this._IdMatriculados;
			}
			set
			{
				if ((this._IdMatriculados != value))
				{
					this.OnIdMatriculadosChanging(value);
					this.SendPropertyChanging();
					this._IdMatriculados = value;
					this.SendPropertyChanged("IdMatriculados");
					this.OnIdMatriculadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="VarChar(6)")]
		public string Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this.OnPeriodoChanging(value);
					this.SendPropertyChanging();
					this._Periodo = value;
					this.SendPropertyChanged("Periodo");
					this.OnPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hombres", DbType="Int")]
		public System.Nullable<int> Hombres
		{
			get
			{
				return this._Hombres;
			}
			set
			{
				if ((this._Hombres != value))
				{
					this.OnHombresChanging(value);
					this.SendPropertyChanging();
					this._Hombres = value;
					this.SendPropertyChanged("Hombres");
					this.OnHombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mujeres", DbType="Int")]
		public System.Nullable<int> Mujeres
		{
			get
			{
				return this._Mujeres;
			}
			set
			{
				if ((this._Mujeres != value))
				{
					this.OnMujeresChanging(value);
					this.SendPropertyChanging();
					this._Mujeres = value;
					this.SendPropertyChanged("Mujeres");
					this.OnMujeresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Matriculados", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.Matriculados.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.Matriculados.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MensajesMaGra")]
	public partial class MensajesMaGra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMensajes;
		
		private string _Titulo;
		
		private string _Mensaje;
		
		private System.Nullable<int> _IdMalla;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMensajesChanging(int value);
    partial void OnIdMensajesChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnMensajeChanging(string value);
    partial void OnMensajeChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    #endregion
		
		public MensajesMaGra()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMensajes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMensajes
		{
			get
			{
				return this._IdMensajes;
			}
			set
			{
				if ((this._IdMensajes != value))
				{
					this.OnIdMensajesChanging(value);
					this.SendPropertyChanging();
					this._IdMensajes = value;
					this.SendPropertyChanged("IdMensajes");
					this.OnIdMensajesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this.OnMensajeChanging(value);
					this.SendPropertyChanging();
					this._Mensaje = value;
					this.SendPropertyChanged("Mensaje");
					this.OnMensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_MensajesMaGra", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.MensajesMaGra.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.MensajesMaGra.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormSoli")]
	public partial class FormSoli : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFormSoli;
		
		private string _Tipo;
		
		private string _FormSoli1;
		
		private System.Nullable<int> _IdMalla;
		
		private string _Nombre;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFormSoliChanging(int value);
    partial void OnIdFormSoliChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnFormSoli1Changing(string value);
    partial void OnFormSoli1Changed();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public FormSoli()
		{
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFormSoli", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFormSoli
		{
			get
			{
				return this._IdFormSoli;
			}
			set
			{
				if ((this._IdFormSoli != value))
				{
					this.OnIdFormSoliChanging(value);
					this.SendPropertyChanging();
					this._IdFormSoli = value;
					this.SendPropertyChanged("IdFormSoli");
					this.OnIdFormSoliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FormSoli", Storage="_FormSoli1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FormSoli1
		{
			get
			{
				return this._FormSoli1;
			}
			set
			{
				if ((this._FormSoli1 != value))
				{
					this.OnFormSoli1Changing(value);
					this.SendPropertyChanging();
					this._FormSoli1 = value;
					this.SendPropertyChanged("FormSoli1");
					this.OnFormSoli1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_FormSoli", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.FormSoli.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.FormSoli.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asignaturas")]
	public partial class Asignaturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAsignatura;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private System.Nullable<decimal> _CompDocenci;
		
		private System.Nullable<decimal> _CompPractico;
		
		private System.Nullable<decimal> _ApreAutonomo;
		
		private System.Nullable<int> _IdCampo;
		
		private System.Nullable<int> _IdUnidad;
		
		private string _Pea;
		
		private System.Nullable<int> _IdMalla;
		
		private System.Nullable<int> _Semestre;
		
		private System.Nullable<int> _Columna;
		
		private EntitySet<Prerrequisito> _Prerrequisito;
		
		private EntityRef<CamposFormacion> _CamposFormacion;
		
		private EntityRef<MallaCurricular> _MallaCurricular;
		
		private EntityRef<Unidades> _Unidades;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAsignaturaChanging(int value);
    partial void OnIdAsignaturaChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCompDocenciChanging(System.Nullable<decimal> value);
    partial void OnCompDocenciChanged();
    partial void OnCompPracticoChanging(System.Nullable<decimal> value);
    partial void OnCompPracticoChanged();
    partial void OnApreAutonomoChanging(System.Nullable<decimal> value);
    partial void OnApreAutonomoChanged();
    partial void OnIdCampoChanging(System.Nullable<int> value);
    partial void OnIdCampoChanged();
    partial void OnIdUnidadChanging(System.Nullable<int> value);
    partial void OnIdUnidadChanged();
    partial void OnPeaChanging(string value);
    partial void OnPeaChanged();
    partial void OnIdMallaChanging(System.Nullable<int> value);
    partial void OnIdMallaChanged();
    partial void OnSemestreChanging(System.Nullable<int> value);
    partial void OnSemestreChanged();
    partial void OnColumnaChanging(System.Nullable<int> value);
    partial void OnColumnaChanged();
    #endregion
		
		public Asignaturas()
		{
			this._Prerrequisito = new EntitySet<Prerrequisito>(new Action<Prerrequisito>(this.attach_Prerrequisito), new Action<Prerrequisito>(this.detach_Prerrequisito));
			this._CamposFormacion = default(EntityRef<CamposFormacion>);
			this._MallaCurricular = default(EntityRef<MallaCurricular>);
			this._Unidades = default(EntityRef<Unidades>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsignatura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAsignatura
		{
			get
			{
				return this._IdAsignatura;
			}
			set
			{
				if ((this._IdAsignatura != value))
				{
					this.OnIdAsignaturaChanging(value);
					this.SendPropertyChanging();
					this._IdAsignatura = value;
					this.SendPropertyChanged("IdAsignatura");
					this.OnIdAsignaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(10)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompDocenci", DbType="Decimal(9,1)")]
		public System.Nullable<decimal> CompDocenci
		{
			get
			{
				return this._CompDocenci;
			}
			set
			{
				if ((this._CompDocenci != value))
				{
					this.OnCompDocenciChanging(value);
					this.SendPropertyChanging();
					this._CompDocenci = value;
					this.SendPropertyChanged("CompDocenci");
					this.OnCompDocenciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompPractico", DbType="Decimal(9,1)")]
		public System.Nullable<decimal> CompPractico
		{
			get
			{
				return this._CompPractico;
			}
			set
			{
				if ((this._CompPractico != value))
				{
					this.OnCompPracticoChanging(value);
					this.SendPropertyChanging();
					this._CompPractico = value;
					this.SendPropertyChanged("CompPractico");
					this.OnCompPracticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApreAutonomo", DbType="Decimal(9,1)")]
		public System.Nullable<decimal> ApreAutonomo
		{
			get
			{
				return this._ApreAutonomo;
			}
			set
			{
				if ((this._ApreAutonomo != value))
				{
					this.OnApreAutonomoChanging(value);
					this.SendPropertyChanging();
					this._ApreAutonomo = value;
					this.SendPropertyChanged("ApreAutonomo");
					this.OnApreAutonomoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCampo", DbType="Int")]
		public System.Nullable<int> IdCampo
		{
			get
			{
				return this._IdCampo;
			}
			set
			{
				if ((this._IdCampo != value))
				{
					if (this._CamposFormacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCampoChanging(value);
					this.SendPropertyChanging();
					this._IdCampo = value;
					this.SendPropertyChanged("IdCampo");
					this.OnIdCampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnidad", DbType="Int")]
		public System.Nullable<int> IdUnidad
		{
			get
			{
				return this._IdUnidad;
			}
			set
			{
				if ((this._IdUnidad != value))
				{
					if (this._Unidades.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUnidadChanging(value);
					this.SendPropertyChanging();
					this._IdUnidad = value;
					this.SendPropertyChanged("IdUnidad");
					this.OnIdUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pea", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Pea
		{
			get
			{
				return this._Pea;
			}
			set
			{
				if ((this._Pea != value))
				{
					this.OnPeaChanging(value);
					this.SendPropertyChanging();
					this._Pea = value;
					this.SendPropertyChanged("Pea");
					this.OnPeaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					if (this._MallaCurricular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMallaChanging(value);
					this.SendPropertyChanging();
					this._IdMalla = value;
					this.SendPropertyChanged("IdMalla");
					this.OnIdMallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre", DbType="Int")]
		public System.Nullable<int> Semestre
		{
			get
			{
				return this._Semestre;
			}
			set
			{
				if ((this._Semestre != value))
				{
					this.OnSemestreChanging(value);
					this.SendPropertyChanging();
					this._Semestre = value;
					this.SendPropertyChanged("Semestre");
					this.OnSemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Columna", DbType="Int")]
		public System.Nullable<int> Columna
		{
			get
			{
				return this._Columna;
			}
			set
			{
				if ((this._Columna != value))
				{
					this.OnColumnaChanging(value);
					this.SendPropertyChanging();
					this._Columna = value;
					this.SendPropertyChanged("Columna");
					this.OnColumnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asignaturas_Prerrequisito", Storage="_Prerrequisito", ThisKey="IdAsignatura", OtherKey="IdAsignatura")]
		public EntitySet<Prerrequisito> Prerrequisito
		{
			get
			{
				return this._Prerrequisito;
			}
			set
			{
				this._Prerrequisito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CamposFormacion_Asignaturas", Storage="_CamposFormacion", ThisKey="IdCampo", OtherKey="IdCampo", IsForeignKey=true)]
		public CamposFormacion CamposFormacion
		{
			get
			{
				return this._CamposFormacion.Entity;
			}
			set
			{
				CamposFormacion previousValue = this._CamposFormacion.Entity;
				if (((previousValue != value) 
							|| (this._CamposFormacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CamposFormacion.Entity = null;
						previousValue.Asignaturas.Remove(this);
					}
					this._CamposFormacion.Entity = value;
					if ((value != null))
					{
						value.Asignaturas.Add(this);
						this._IdCampo = value.IdCampo;
					}
					else
					{
						this._IdCampo = default(Nullable<int>);
					}
					this.SendPropertyChanged("CamposFormacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MallaCurricular_Asignaturas", Storage="_MallaCurricular", ThisKey="IdMalla", OtherKey="IdMalla", IsForeignKey=true)]
		public MallaCurricular MallaCurricular
		{
			get
			{
				return this._MallaCurricular.Entity;
			}
			set
			{
				MallaCurricular previousValue = this._MallaCurricular.Entity;
				if (((previousValue != value) 
							|| (this._MallaCurricular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MallaCurricular.Entity = null;
						previousValue.Asignaturas.Remove(this);
					}
					this._MallaCurricular.Entity = value;
					if ((value != null))
					{
						value.Asignaturas.Add(this);
						this._IdMalla = value.IdMalla;
					}
					else
					{
						this._IdMalla = default(Nullable<int>);
					}
					this.SendPropertyChanged("MallaCurricular");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Unidades_Asignaturas", Storage="_Unidades", ThisKey="IdUnidad", OtherKey="IdUnidades", IsForeignKey=true)]
		public Unidades Unidades
		{
			get
			{
				return this._Unidades.Entity;
			}
			set
			{
				Unidades previousValue = this._Unidades.Entity;
				if (((previousValue != value) 
							|| (this._Unidades.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Unidades.Entity = null;
						previousValue.Asignaturas.Remove(this);
					}
					this._Unidades.Entity = value;
					if ((value != null))
					{
						value.Asignaturas.Add(this);
						this._IdUnidad = value.IdUnidades;
					}
					else
					{
						this._IdUnidad = default(Nullable<int>);
					}
					this.SendPropertyChanged("Unidades");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prerrequisito(Prerrequisito entity)
		{
			this.SendPropertyChanging();
			entity.Asignaturas = this;
		}
		
		private void detach_Prerrequisito(Prerrequisito entity)
		{
			this.SendPropertyChanging();
			entity.Asignaturas = null;
		}
	}
	
	public partial class proalmColumnaResult
	{
		
		private System.Nullable<int> _Columna;
		
		public proalmColumnaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Columna", DbType="Int")]
		public System.Nullable<int> Columna
		{
			get
			{
				return this._Columna;
			}
			set
			{
				if ((this._Columna != value))
				{
					this._Columna = value;
				}
			}
		}
	}
	
	public partial class proalmSemestreResult
	{
		
		private System.Nullable<int> _Semestre;
		
		public proalmSemestreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre", DbType="Int")]
		public System.Nullable<int> Semestre
		{
			get
			{
				return this._Semestre;
			}
			set
			{
				if ((this._Semestre != value))
				{
					this._Semestre = value;
				}
			}
		}
	}
	
	public partial class palmaTodasAsignaturasResult
	{
		
		private int _IdAsignatura;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private System.Nullable<decimal> _CompDocenci;
		
		private System.Nullable<decimal> _CompPractico;
		
		private System.Nullable<decimal> _ApreAutonomo;
		
		private System.Nullable<int> _IdCampo;
		
		private System.Nullable<int> _IdUnidad;
		
		private string _Pea;
		
		private System.Nullable<int> _IdMalla;
		
		private System.Nullable<int> _Semestre;
		
		private System.Nullable<int> _Columna;
		
		public palmaTodasAsignaturasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsignatura", DbType="Int NOT NULL")]
		public int IdAsignatura
		{
			get
			{
				return this._IdAsignatura;
			}
			set
			{
				if ((this._IdAsignatura != value))
				{
					this._IdAsignatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(10)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompDocenci", DbType="Decimal(9,1)")]
		public System.Nullable<decimal> CompDocenci
		{
			get
			{
				return this._CompDocenci;
			}
			set
			{
				if ((this._CompDocenci != value))
				{
					this._CompDocenci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompPractico", DbType="Decimal(9,1)")]
		public System.Nullable<decimal> CompPractico
		{
			get
			{
				return this._CompPractico;
			}
			set
			{
				if ((this._CompPractico != value))
				{
					this._CompPractico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApreAutonomo", DbType="Decimal(9,1)")]
		public System.Nullable<decimal> ApreAutonomo
		{
			get
			{
				return this._ApreAutonomo;
			}
			set
			{
				if ((this._ApreAutonomo != value))
				{
					this._ApreAutonomo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCampo", DbType="Int")]
		public System.Nullable<int> IdCampo
		{
			get
			{
				return this._IdCampo;
			}
			set
			{
				if ((this._IdCampo != value))
				{
					this._IdCampo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnidad", DbType="Int")]
		public System.Nullable<int> IdUnidad
		{
			get
			{
				return this._IdUnidad;
			}
			set
			{
				if ((this._IdUnidad != value))
				{
					this._IdUnidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pea", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Pea
		{
			get
			{
				return this._Pea;
			}
			set
			{
				if ((this._Pea != value))
				{
					this._Pea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalla", DbType="Int")]
		public System.Nullable<int> IdMalla
		{
			get
			{
				return this._IdMalla;
			}
			set
			{
				if ((this._IdMalla != value))
				{
					this._IdMalla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semestre", DbType="Int")]
		public System.Nullable<int> Semestre
		{
			get
			{
				return this._Semestre;
			}
			set
			{
				if ((this._Semestre != value))
				{
					this._Semestre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Columna", DbType="Int")]
		public System.Nullable<int> Columna
		{
			get
			{
				return this._Columna;
			}
			set
			{
				if ((this._Columna != value))
				{
					this._Columna = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
